// Code generated by protoc-gen-go. DO NOT EDIT.
// source: snowflake.proto

/*
Package fpay_snowflake is a generated protocol buffer package.

It is generated from these files:
	snowflake.proto

It has these top-level messages:
	Request
	Response
*/
package fpay_snowflake

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 请求结构体
type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 返回结构体
type Response struct {
	Uniqid int64 `protobuf:"varint,1,opt,name=uniqid" json:"uniqid,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetUniqid() int64 {
	if m != nil {
		return m.Uniqid
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "fpay.snowflake.Request")
	proto.RegisterType((*Response)(nil), "fpay.snowflake.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SnowflakeService service

type SnowflakeServiceClient interface {
	Generate(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type snowflakeServiceClient struct {
	cc *grpc.ClientConn
}

func NewSnowflakeServiceClient(cc *grpc.ClientConn) SnowflakeServiceClient {
	return &snowflakeServiceClient{cc}
}

func (c *snowflakeServiceClient) Generate(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/fpay.snowflake.SnowflakeService/Generate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SnowflakeService service

type SnowflakeServiceServer interface {
	Generate(context.Context, *Request) (*Response, error)
}

func RegisterSnowflakeServiceServer(s *grpc.Server, srv SnowflakeServiceServer) {
	s.RegisterService(&_SnowflakeService_serviceDesc, srv)
}

func _SnowflakeService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fpay.snowflake.SnowflakeService/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeServiceServer).Generate(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _SnowflakeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fpay.snowflake.SnowflakeService",
	HandlerType: (*SnowflakeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _SnowflakeService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snowflake.proto",
}

func init() { proto.RegisterFile("snowflake.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xce, 0xcb, 0x2f,
	0x4f, 0xcb, 0x49, 0xcc, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4b, 0x2b, 0x48,
	0xac, 0xd4, 0x83, 0x8b, 0x2a, 0x71, 0x72, 0xb1, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28,
	0x29, 0x71, 0x71, 0x04, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x71, 0xb1, 0x95,
	0xe6, 0x65, 0x16, 0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x79, 0x46, 0xc1,
	0x5c, 0x02, 0xc1, 0x30, 0xbd, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xf6, 0x5c, 0x1c,
	0xee, 0xa9, 0x79, 0xa9, 0x45, 0x89, 0x25, 0xa9, 0x42, 0xe2, 0x7a, 0xa8, 0xe6, 0xeb, 0x41, 0x0d,
	0x97, 0x92, 0xc0, 0x94, 0x80, 0x58, 0xa5, 0xc4, 0x90, 0xc4, 0x06, 0x76, 0x9a, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x09, 0xad, 0x9f, 0xc4, 0xad, 0x00, 0x00, 0x00,
}
